### ISSUE TITLE
Plugin causing 500 internal error on admin-ajax.php using WordPress 4.6.1

### ISSUE THREAD

**Issue by BeyondTheLoop** [petitphp/facetwp-monthly#1]
I'm not sure if this plugin is being maintained or not but I'm getting the error described in the title. 
FacetWP version 2.6.3.

**Comment by petitphp** [comment]
Hello,

Thanks for the issue, looking into it.

**Comment by petitphp** [comment]
I just release an update ([1.1.0](https://github.com/petitphp/facetwp-monthly/releases/tag/1.1.0)) that fix the error.

**Comment by BeyondTheLoop** [comment]
Thank you very much, error is gone with the update. Keep up the good work :)
